### ISSUE TITLE
too much power.

### ISSUE THREAD

**Issue by dynamicc15** [Salvito7/arduino-hid-bruteforce#2]
when i connect to iphone 4s it says ''cannot use device arduino leonard requires too much power." but the board still on and working, but not typing anything on the iphone. when i test it with a pc it works fine. any ideas? im using an usb C version board.

**Comment by Salvito7** [comment]
What kind of adapter are you using to connect the board to the iPhone?

**Comment by dynamicc15** [comment]
Thanks for your response! Im using the original apple camera kit. Its working now. I plugged in an usb hub in the adapter and then connected the board to the hub and its working now! Thank you! Now i have some problem with the arduino uno pwned dfu board. If u could help me with that it would be nice!

**Comment by Salvito7** [comment]
I remember when I built the pwned dfu board, the whole setup was very buggy and didnt always work.
Sometimes it took three connects/disconnects from the iOS device to the board or I had to power cycle the arduino itself multiple times before it worked correctly. So i dont know how much i can help you with that, but I can try.

**Comment by dynamicc15** [comment]
Did u used an priginal arduino uno? Because i bought it mine from aliexpress. I dont know if that matters. Do u have discord btw? So we can chat there, its easier

**Comment by Salvito7** [comment]
I used an original arduino but i don't know if that matters
My discord is salvito_
